services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
    ports:
      - 3000:3000/tcp
    environment:
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_DEFAULT_APP_MODE: development
      GF_PLUGINS_PREINSTALL: marcusolsson-static-datasource
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /etc/grafana/provisioning/dashboards/home.json
    healthcheck:
      test: ['CMD-SHELL', 'wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  timescale:
    image: timescale/timescaledb:latest-pg14
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./timescale-setup:/docker-entrypoint-initdb.d
    profiles:
      - dev
      - playwright

  server:
    build:
      context: ./timescale-setup
    ports:
      - 3001:3001/tcp
    depends_on:
      - timescale
    environment:
      WAIT_HOSTS: timescale:5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: timescale
    profiles:
      - dev
      - playwright

  playwright:
    build:
      context: .
      dockerfile: test/Dockerfile
    environment:
      - GRAFANA_URL=http://grafana:3000
    volumes:
      - ./test:/app/test
      - ./playwright-report:/app/playwright-report
    depends_on:
      grafana:
        condition: service_healthy
      timescale:
        condition: service_started
      server:
        condition: service_started
    profiles:
      - playwright
