services:
  grafana:
    user: root
    container_name: 'grafana-business-variable-panel'
    image: grafana/${GRAFANA_IMAGE:-grafana-enterprise}:${GRAFANA_VERSION:-latest}
    ports:
      - 3000:3000/tcp
    volumes:
      - ../dist:/var/lib/grafana/plugins/volkovlabs-variable-panel
      - ../provisioning:/etc/grafana/provisioning
    environment:
      NODE_ENV: development
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_ANONYMOUS_ENABLED: ${ANONYMOUS_AUTH_ENABLED:-true}
      GF_AUTH_BASIC_ENABLED: 'false'
      GF_DEFAULT_APP_MODE: development
      GF_LOG_FILTERS: plugin.volkovlabs-variable-panel:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: volkovlabs-variable-panel
      GF_INSTALL_PLUGINS: marcusolsson-static-datasource
