name: Plugins - CI

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    uses: grafana/plugin-ci-workflows/.github/workflows/ci.yml@ci-cd-workflows/v8.0.1
    permissions:
      contents: read
      pull-requests: read
      attestations: write
      id-token: write
    with:
      plugin-version-suffix: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || '' }}
      run-playwright-with-grafana-dependency: ">=12.3.0"
      run-playwright: false
      run-playwright-docker: true
      playwright-docker-compose-file: docker-compose.yaml
      upload-playwright-artifacts: true
      run-playwright-with-skip-grafana-dev-image: false
      run-playwright-with-skip-grafana-react-19-preview-image: false
      signature-type: community
